apiVersion: skaffold/v2beta14
kind: Config
metadata:
  name: ampel-service
build:
  artifacts:
    - image: registry.projectdw.de/ampel-service
      context: .
      jib:
        project: de.projectdw:ampel-service
        args: [ -DskipTests ]
        type: maven
deploy:
  kubectl:
    manifests:
      - kubernetes/service/ampel-deployment.yaml
      - kubernetes/service/ampel-service.yaml

