apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-syse

spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb-syse
        track: stable
    spec:
      containers:
        - name: mongodb
          image: mongo:4.2
          ports:
            - containerPort: 27017
          volumeMounts:
            - mountPath: /data/db
              name: mongodb-syse

          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: admin
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: admin

  volumeClaimTemplates:
    - metadata:
        name: mongodb-syse
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: longhorn
        resources:
          requests:
            storage: 3Gi

  selector:
    matchLabels:
      app: mongodb-syse
  serviceName: mongodb-syse

