# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  upload-artifacts-and-image:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Set up JDK 16 for deploy to github packages
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '16'
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: "https://registry.projectdw.de"
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: maven-settings-xml-action
        uses: whelk-io/maven-settings-xml-action@v4
        with:
          repositories: '[{ "id": "vsys", "url": "https://artifactory.projectdw.de/repository/vsys/" }]'
          servers: '[{ "id": "vsys", "username": "${{ secrets.ARCHIVA_USERNAME }}", "password": "${{ secrets.ARCHIVA_PASSWORD }}" }]'
    

      - name: Publish to Private Archiva
        run: |
          cd $GITHUB_WORKSPACE
          echo(ls -lisa)
          mvn deploy	-DskipTests
      
      - name: JIB Build
        run: mvn jib:build
